#! /bin/bash

# python3 grader/error_diffusion.py grader/image/grayscale_image/grayscale_lenna_512.png validate.png

# python3 grader/bw_similarity.py output/output_no_thread.png validate.png
python3 grader/bw_similarity.py output/output_2_thread.png output/output_no_thread.png
