#! /bin/bash


java src/Main.java OS_midterm_grader/image/grayscale_image/grayscale_lenna_512.png output.png
python3 OS_midterm_grader/error_diffusion.py OS_midterm_grader/image/grayscale_image/grayscale_lenna_512.png validate.png

python3 OS_midterm_grader/bw_similarity.py output.png validate.png



